name: Release Licenser

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    name: Build Windows DLL
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build DLL
        run: cargo build --release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: windows-dll
          path: target/release/*.dll

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build in CentOS7 container
        run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace \
            centos:7.9.2009 \
            bash -c "
              # fix yum repo for CentOS 7 (official repo is dead)
              sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo &&
              sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo &&

              yum clean all &&
              yum makecache &&

              yum groupinstall -y 'Development Tools' &&
              yum install -y openssl-devel wget curl &&

              curl https://sh.rustup.rs -sSf | sh -s -- -y &&
              source \$HOME/.cargo/env &&
              rustup target add x86_64-unknown-linux-gnu &&

              cargo build --release --target x86_64-unknown-linux-gnu
            "

      - name: Upload SO
        uses: actions/upload-artifact@v4
        with:
          name: linux-so
          path: target/x86_64-unknown-linux-gnu/release/*.so




  build-mac:
    name: Build Mac Dylib
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Build Dylib
        run: cargo build --release --target x86_64-apple-darwin

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: mac-dylib
          path: target/x86_64-apple-darwin/release/*.dylib

  publish:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
